require 'jar_dependencies'
JBUNDLER_LOCAL_REPO = Jars.home
JBUNDLER_JRUBY_CLASSPATH = []
JBUNDLER_JRUBY_CLASSPATH.freeze
JBUNDLER_TEST_CLASSPATH = []
JBUNDLER_TEST_CLASSPATH.freeze
JBUNDLER_CLASSPATH = []
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/orientechnologies/orientdb-server/2.1.9/orientdb-server-2.1.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/asm/asm-util/3.2/asm-util-3.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-digester/commons-digester/1.8/commons-digester-1.8.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/jline/jline/0.9.94/jline-0.9.94.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/yaml/snakeyaml/1.14/snakeyaml-1.14.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/ivy/ivy/2.3.0/ivy-2.3.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/tinkerpop/blueprints/blueprints-core/2.6.0/blueprints-core-2.6.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-lang/commons-lang/2.4/commons-lang-2.4.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/asm/asm-commons/3.2/asm-commons-3.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/ant/ant-launcher/1.8.3/ant-launcher-1.8.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/activation/activation/1.1/activation-1.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/mail/mail/1.4/mail-1.4.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/antlr/antlr/2.7.7/antlr-2.7.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/tinkerpop/pipes/2.6.0/pipes-2.6.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/codehaus/groovy/groovy/1.8.9/groovy-1.8.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4.1/concurrentlinkedhashmap-lru-1.4.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/net/java/dev/jna/jna/4.0.0/jna-4.0.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/asm/asm-tree/3.2/asm-tree-3.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/ant/ant/1.8.3/ant-1.8.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/orientechnologies/orientdb-core/2.1.9/orientdb-core-2.1.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/orientechnologies/orientdb-object/2.1.9/orientdb-object-2.1.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/net/java/dev/jna/jna-platform/4.0.0/jna-platform-4.0.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/orientechnologies/orientdb-tools/2.1.9/orientdb-tools-2.1.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/javassist/javassist/3.16.1-GA/javassist-3.16.1-GA.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/tinkerpop/gremlin/gremlin-java/2.6.0/gremlin-java-2.6.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/xerial/snappy/snappy-java/1.1.0.1/snappy-java-1.1.0.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/orientechnologies/orientdb-graphdb/2.1.9/orientdb-graphdb-2.1.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-databind/2.2.3/jackson-databind-2.2.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/orientechnologies/orientdb-client/2.1.9/orientdb-client-2.1.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/orientechnologies/orientdb-enterprise/2.1.9/orientdb-enterprise-2.1.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/fusesource/jansi/jansi/1.5/jansi-1.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/hibernate/javax/persistence/hibernate-jpa-2.0-api/1.0.0.Final/hibernate-jpa-2.0-api-1.0.0.Final.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-annotations/2.2.3/jackson-annotations-2.2.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/tinkerpop/gremlin/gremlin-groovy/2.6.0/gremlin-groovy-2.6.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/codehaus/jettison/jettison/1.3.3/jettison-1.3.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-core/2.2.3/jackson-core-2.2.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/stax/stax-api/1.0.1/stax-api-1.0.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/carrotsearch/hppc/0.6.0/hppc-0.6.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/asm/asm/3.2/asm-3.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/asm/asm-analysis/3.2/asm-analysis-3.2.jar')
JBUNDLER_CLASSPATH.freeze
